name: deployment
on: 
  push:
    branches:
      - main
      - 'dev-*'
      - feature/**
    paths-ignore:
      - ./github/workflows/*

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
